package com.exercise.demo.model.po.order;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table article_info
 */
public class ArticleInfo {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     * Database Column Remarks:
     *   标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   作者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     * Database Column Remarks:
     *   重要性
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.important_level
     *
     * @mbg.generated
     */
    private Integer importantLevel;

    /**
     * Database Column Remarks:
     *   阅读数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.read_count
     *
     * @mbg.generated
     */
    private Long readCount;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.statusDescription
     *
     * @mbg.generated
     */
    private String statusdescription;

    /**
     * Database Column Remarks:
     *   文章内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   国家
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     * Database Column Remarks:
     *   审核人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.auditor
     *
     * @mbg.generated
     */
    private String auditor;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.id
     *
     * @return the value of article_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.id
     *
     * @param id the value for article_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.category_id
     *
     * @return the value of article_info.category_id
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.category_id
     *
     * @param categoryId the value for article_info.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.title
     *
     * @return the value of article_info.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.title
     *
     * @param title the value for article_info.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.author
     *
     * @return the value of article_info.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.author
     *
     * @param author the value for article_info.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.important_level
     *
     * @return the value of article_info.important_level
     *
     * @mbg.generated
     */
    public Integer getImportantLevel() {
        return importantLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.important_level
     *
     * @param importantLevel the value for article_info.important_level
     *
     * @mbg.generated
     */
    public void setImportantLevel(Integer importantLevel) {
        this.importantLevel = importantLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.read_count
     *
     * @return the value of article_info.read_count
     *
     * @mbg.generated
     */
    public Long getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.read_count
     *
     * @param readCount the value for article_info.read_count
     *
     * @mbg.generated
     */
    public void setReadCount(Long readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.state
     *
     * @return the value of article_info.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.state
     *
     * @param state the value for article_info.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.statusDescription
     *
     * @return the value of article_info.statusDescription
     *
     * @mbg.generated
     */
    public String getStatusdescription() {
        return statusdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.statusDescription
     *
     * @param statusdescription the value for article_info.statusDescription
     *
     * @mbg.generated
     */
    public void setStatusdescription(String statusdescription) {
        this.statusdescription = statusdescription == null ? null : statusdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.content
     *
     * @return the value of article_info.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.content
     *
     * @param content the value for article_info.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.country
     *
     * @return the value of article_info.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.country
     *
     * @param country the value for article_info.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.auditor
     *
     * @return the value of article_info.auditor
     *
     * @mbg.generated
     */
    public String getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.auditor
     *
     * @param auditor the value for article_info.auditor
     *
     * @mbg.generated
     */
    public void setAuditor(String auditor) {
        this.auditor = auditor == null ? null : auditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_info.create_time
     *
     * @return the value of article_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_info.create_time
     *
     * @param createTime the value for article_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}