package com.exercise.demo.model.po.order;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_order_extend
 */
public class OrderExtend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     * Database Column Remarks:
     *   到店日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.arrive_date
     *
     * @mbg.generated
     */
    private Date arriveDate;

    /**
     * Database Column Remarks:
     *   离店日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.leave_date
     *
     * @mbg.generated
     */
    private Date leaveDate;

    /**
     * Database Column Remarks:
     *   房源id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.house_id
     *
     * @mbg.generated
     */
    private Long houseId;

    /**
     * Database Column Remarks:
     *   房源名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.house_name
     *
     * @mbg.generated
     */
    private String houseName;

    /**
     * Database Column Remarks:
     *   供应产品Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.supplier_product_id
     *
     * @mbg.generated
     */
    private String supplierProductId;

    /**
     * Database Column Remarks:
     *   供应商房型Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.supplier_house_id
     *
     * @mbg.generated
     */
    private String supplierHouseId;

    /**
     * Database Column Remarks:
     *   房东id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.landloard_id
     *
     * @mbg.generated
     */
    private Long landloardId;

    /**
     * Database Column Remarks:
     *   公寓名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.apartment_name
     *
     * @mbg.generated
     */
    private String apartmentName;

    /**
     * Database Column Remarks:
     *   公寓id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.apartment_id
     *
     * @mbg.generated
     */
    private Long apartmentId;

    /**
     * Database Column Remarks:
     *   预付规则
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.rule
     *
     * @mbg.generated
     */
    private String rule;

    /**
     * Database Column Remarks:
     *   支付状态（1 支付成功 0 未支付 2 支付失败 3其他） 默认为0
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.pay_status
     *
     * @mbg.generated
     */
    private Byte payStatus;

    /**
     * Database Column Remarks:
     *   支付情况描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.pay_des
     *
     * @mbg.generated
     */
    private String payDes;

    /**
     * Database Column Remarks:
     *   轨迹号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.trace_id
     *
     * @mbg.generated
     */
    private String traceId;

    /**
     * Database Column Remarks:
     *   设备号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.app_device_id
     *
     * @mbg.generated
     */
    private String appDeviceId;

    /**
     * Database Column Remarks:
     *   客户端类型(0:未知,1:独立包IOS,2:插件IOS,3:独立包安卓,4:插件安卓,5:艺龙酒店IOS,6:艺龙酒店安卓,7:H5,8:手Q,9:WX,10:酒店直连,11:QQ会员 ,12:同程旅游IOS,13:同程旅游安卓,14:懒猫民宿小程序)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.app_client_type
     *
     * @mbg.generated
     */
    private String appClientType;

    /**
     * Database Column Remarks:
     *   app版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.app_version
     *
     * @mbg.generated
     */
    private String appVersion;

    /**
     * Database Column Remarks:
     *   设备ip
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.client_ip
     *
     * @mbg.generated
     */
    private String clientIp;

    /**
     * Database Column Remarks:
     *   会员手机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.lodger_mobile
     *
     * @mbg.generated
     */
    private String lodgerMobile;

    /**
     * Database Column Remarks:
     *   会员名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.lodger_name
     *
     * @mbg.generated
     */
    private String lodgerName;

    /**
     * Database Column Remarks:
     *   房东名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.landlord_name
     *
     * @mbg.generated
     */
    private String landlordName;

    /**
     * Database Column Remarks:
     *   房东手机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.landlord_mobile
     *
     * @mbg.generated
     */
    private String landlordMobile;

    /**
     * Database Column Remarks:
     *   入住人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.custom_name
     *
     * @mbg.generated
     */
    private String customName;

    /**
     * Database Column Remarks:
     *   客人人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.custom_count
     *
     * @mbg.generated
     */
    private Short customCount;

    /**
     * Database Column Remarks:
     *   罚金
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.fine
     *
     * @mbg.generated
     */
    private BigDecimal fine;

    /**
     * Database Column Remarks:
     *   房源所属城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.house_belong_city
     *
     * @mbg.generated
     */
    private String houseBelongCity;

    /**
     * Database Column Remarks:
     *   是否已经评论（1 已评论 0 未评论）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.is_comment
     *
     * @mbg.generated
     */
    private Byte isComment;

    /**
     * Database Column Remarks:
     *   房东删除订单，后端假删除(1 删除 0 未删除)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.is_delete_landlord
     *
     * @mbg.generated
     */
    private Byte isDeleteLandlord;

    /**
     * Database Column Remarks:
     *   同程APP行程订单(0：未删除 1：已删除)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.is_delete_trip
     *
     * @mbg.generated
     */
    private Byte isDeleteTrip;

    /**
     * Database Column Remarks:
     *   用户删除订单，后端假删除(1 删除 0 未删除)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.is_delete
     *
     * @mbg.generated
     */
    private Byte isDelete;

    /**
     * Database Column Remarks:
     *   房客给房东留言
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.lodger_to_landlord_note
     *
     * @mbg.generated
     */
    private String lodgerToLandlordNote;

    /**
     * Database Column Remarks:
     *   房东elong卡号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.landlord_card_no
     *
     * @mbg.generated
     */
    private Long landlordCardNo;

    /**
     * Database Column Remarks:
     *   确认已入住时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.check_in_time
     *
     * @mbg.generated
     */
    private Date checkInTime;

    /**
     * Database Column Remarks:
     *   实际收入（服务费）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.fee
     *
     * @mbg.generated
     */
    private BigDecimal fee;

    /**
     * Database Column Remarks:
     *   房客艺龙卡号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.lodger_card_no
     *
     * @mbg.generated
     */
    private Long lodgerCardNo;

    /**
     * Database Column Remarks:
     *   接单确认类型：0 手动接单 1 立即接单
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.accept_type
     *
     * @mbg.generated
     */
    private Byte acceptType;

    /**
     * Database Column Remarks:
     *   订单状态历史：1-接单成功，2-支付成功，4-预订成功
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.order_status_history
     *
     * @mbg.generated
     */
    private Long orderStatusHistory;

    /**
     * Database Column Remarks:
     *   房源所属城市名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.house_belong_city_name
     *
     * @mbg.generated
     */
    private String houseBelongCityName;

    /**
     * Database Column Remarks:
     *   活动id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.activity_id
     *
     * @mbg.generated
     */
    private Integer activityId;

    /**
     * Database Column Remarks:
     *   入口id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.of_id
     *
     * @mbg.generated
     */
    private Integer ofId;

    /**
     * Database Column Remarks:
     *   需要退给房东的罚金
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.fine_belong_landlord
     *
     * @mbg.generated
     */
    private BigDecimal fineBelongLandlord;

    /**
     * Database Column Remarks:
     *   在线押金
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.deposit_online
     *
     * @mbg.generated
     */
    private BigDecimal depositOnline;

    /**
     * Database Column Remarks:
     *   线下押金
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.deposit_offline
     *
     * @mbg.generated
     */
    private BigDecimal depositOffline;

    /**
     * Database Column Remarks:
     *   需要催单数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.need_reminder_number
     *
     * @mbg.generated
     */
    private String needReminderNumber;

    /**
     * Database Column Remarks:
     *   实际催单数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.real_reminder_number
     *
     * @mbg.generated
     */
    private String realReminderNumber;

    /**
     * Database Column Remarks:
     *   订单业务线来源
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.ch_id
     *
     * @mbg.generated
     */
    private String chId;

    /**
     * Database Column Remarks:
     *   页面某区域的点位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.if_id
     *
     * @mbg.generated
     */
    private String ifId;

    /**
     * Database Column Remarks:
     *   内部业务线id,10001民宿,10002短租
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.business_type_id
     *
     * @mbg.generated
     */
    private String businessTypeId;

    /**
     * Database Column Remarks:
     *   商圈名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.district_name
     *
     * @mbg.generated
     */
    private String districtName;

    /**
     * Database Column Remarks:
     *   百度纬度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.baidu_lat
     *
     * @mbg.generated
     */
    private BigDecimal baiduLat;

    /**
     * Database Column Remarks:
     *   百度经度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.baidu_lon
     *
     * @mbg.generated
     */
    private BigDecimal baiduLon;

    /**
     * Database Column Remarks:
     *   房东头像地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.avatar_url
     *
     * @mbg.generated
     */
    private String avatarUrl;

    /**
     * Database Column Remarks:
     *   房源封面url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.house_imag_url
     *
     * @mbg.generated
     */
    private String houseImagUrl;

    /**
     * Database Column Remarks:
     *   房客头像url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.lodger_url
     *
     * @mbg.generated
     */
    private String lodgerUrl;

    /**
     * Database Column Remarks:
     *   取消订单打点类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.type
     *
     * @mbg.generated
     */
    private Short type;

    /**
     * Database Column Remarks:
     *   拒单类型 0其他,1满房，2订单价格太低，3预定时间过早,4房客特殊要求无法满足
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.close_type
     *
     * @mbg.generated
     */
    private String closeType;

    /**
     * Database Column Remarks:
     *   拒单备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.refuse_desc
     *
     * @mbg.generated
     */
    private String refuseDesc;

    /**
     * Database Column Remarks:
     *   mvt打点类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.mvt_config
     *
     * @mbg.generated
     */
    private String mvtConfig;

    /**
     * Database Column Remarks:
     *   google纬度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.google_lat
     *
     * @mbg.generated
     */
    private BigDecimal googleLat;

    /**
     * Database Column Remarks:
     *   google经度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.google_lon
     *
     * @mbg.generated
     */
    private BigDecimal googleLon;

    /**
     * Database Column Remarks:
     *   所属行政id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.district_id
     *
     * @mbg.generated
     */
    private String districtId;

    /**
     * Database Column Remarks:
     *   ch值，区分同程
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.ch_content
     *
     * @mbg.generated
     */
    private String chContent;

    /**
     * Database Column Remarks:
     *   所属行政区id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.business_id
     *
     * @mbg.generated
     */
    private String businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend._timestamp
     *
     * @mbg.generated
     */
    private Date timestamp;

    /**
     * Database Column Remarks:
     *   支付比例
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.pay_percent
     *
     * @mbg.generated
     */
    private BigDecimal payPercent;

    /**
     * Database Column Remarks:
     *   省份ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.house_belong_province
     *
     * @mbg.generated
     */
    private Long houseBelongProvince;

    /**
     * Database Column Remarks:
     *   省份名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.house_belong_province_name
     *
     * @mbg.generated
     */
    private String houseBelongProvinceName;

    /**
     * Database Column Remarks:
     *   扩展字段（Json格式，数据组用）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_extend.extend_info
     *
     * @mbg.generated
     */
    private String extendInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.id
     *
     * @return the value of tb_order_extend.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.id
     *
     * @param id the value for tb_order_extend.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.order_id
     *
     * @return the value of tb_order_extend.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.order_id
     *
     * @param orderId the value for tb_order_extend.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.arrive_date
     *
     * @return the value of tb_order_extend.arrive_date
     *
     * @mbg.generated
     */
    public Date getArriveDate() {
        return arriveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.arrive_date
     *
     * @param arriveDate the value for tb_order_extend.arrive_date
     *
     * @mbg.generated
     */
    public void setArriveDate(Date arriveDate) {
        this.arriveDate = arriveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.leave_date
     *
     * @return the value of tb_order_extend.leave_date
     *
     * @mbg.generated
     */
    public Date getLeaveDate() {
        return leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.leave_date
     *
     * @param leaveDate the value for tb_order_extend.leave_date
     *
     * @mbg.generated
     */
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.house_id
     *
     * @return the value of tb_order_extend.house_id
     *
     * @mbg.generated
     */
    public Long getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.house_id
     *
     * @param houseId the value for tb_order_extend.house_id
     *
     * @mbg.generated
     */
    public void setHouseId(Long houseId) {
        this.houseId = houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.house_name
     *
     * @return the value of tb_order_extend.house_name
     *
     * @mbg.generated
     */
    public String getHouseName() {
        return houseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.house_name
     *
     * @param houseName the value for tb_order_extend.house_name
     *
     * @mbg.generated
     */
    public void setHouseName(String houseName) {
        this.houseName = houseName == null ? null : houseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.supplier_product_id
     *
     * @return the value of tb_order_extend.supplier_product_id
     *
     * @mbg.generated
     */
    public String getSupplierProductId() {
        return supplierProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.supplier_product_id
     *
     * @param supplierProductId the value for tb_order_extend.supplier_product_id
     *
     * @mbg.generated
     */
    public void setSupplierProductId(String supplierProductId) {
        this.supplierProductId = supplierProductId == null ? null : supplierProductId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.supplier_house_id
     *
     * @return the value of tb_order_extend.supplier_house_id
     *
     * @mbg.generated
     */
    public String getSupplierHouseId() {
        return supplierHouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.supplier_house_id
     *
     * @param supplierHouseId the value for tb_order_extend.supplier_house_id
     *
     * @mbg.generated
     */
    public void setSupplierHouseId(String supplierHouseId) {
        this.supplierHouseId = supplierHouseId == null ? null : supplierHouseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.landloard_id
     *
     * @return the value of tb_order_extend.landloard_id
     *
     * @mbg.generated
     */
    public Long getLandloardId() {
        return landloardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.landloard_id
     *
     * @param landloardId the value for tb_order_extend.landloard_id
     *
     * @mbg.generated
     */
    public void setLandloardId(Long landloardId) {
        this.landloardId = landloardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.apartment_name
     *
     * @return the value of tb_order_extend.apartment_name
     *
     * @mbg.generated
     */
    public String getApartmentName() {
        return apartmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.apartment_name
     *
     * @param apartmentName the value for tb_order_extend.apartment_name
     *
     * @mbg.generated
     */
    public void setApartmentName(String apartmentName) {
        this.apartmentName = apartmentName == null ? null : apartmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.apartment_id
     *
     * @return the value of tb_order_extend.apartment_id
     *
     * @mbg.generated
     */
    public Long getApartmentId() {
        return apartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.apartment_id
     *
     * @param apartmentId the value for tb_order_extend.apartment_id
     *
     * @mbg.generated
     */
    public void setApartmentId(Long apartmentId) {
        this.apartmentId = apartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.rule
     *
     * @return the value of tb_order_extend.rule
     *
     * @mbg.generated
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.rule
     *
     * @param rule the value for tb_order_extend.rule
     *
     * @mbg.generated
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.pay_status
     *
     * @return the value of tb_order_extend.pay_status
     *
     * @mbg.generated
     */
    public Byte getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.pay_status
     *
     * @param payStatus the value for tb_order_extend.pay_status
     *
     * @mbg.generated
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.pay_des
     *
     * @return the value of tb_order_extend.pay_des
     *
     * @mbg.generated
     */
    public String getPayDes() {
        return payDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.pay_des
     *
     * @param payDes the value for tb_order_extend.pay_des
     *
     * @mbg.generated
     */
    public void setPayDes(String payDes) {
        this.payDes = payDes == null ? null : payDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.trace_id
     *
     * @return the value of tb_order_extend.trace_id
     *
     * @mbg.generated
     */
    public String getTraceId() {
        return traceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.trace_id
     *
     * @param traceId the value for tb_order_extend.trace_id
     *
     * @mbg.generated
     */
    public void setTraceId(String traceId) {
        this.traceId = traceId == null ? null : traceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.app_device_id
     *
     * @return the value of tb_order_extend.app_device_id
     *
     * @mbg.generated
     */
    public String getAppDeviceId() {
        return appDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.app_device_id
     *
     * @param appDeviceId the value for tb_order_extend.app_device_id
     *
     * @mbg.generated
     */
    public void setAppDeviceId(String appDeviceId) {
        this.appDeviceId = appDeviceId == null ? null : appDeviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.app_client_type
     *
     * @return the value of tb_order_extend.app_client_type
     *
     * @mbg.generated
     */
    public String getAppClientType() {
        return appClientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.app_client_type
     *
     * @param appClientType the value for tb_order_extend.app_client_type
     *
     * @mbg.generated
     */
    public void setAppClientType(String appClientType) {
        this.appClientType = appClientType == null ? null : appClientType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.app_version
     *
     * @return the value of tb_order_extend.app_version
     *
     * @mbg.generated
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.app_version
     *
     * @param appVersion the value for tb_order_extend.app_version
     *
     * @mbg.generated
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion == null ? null : appVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.client_ip
     *
     * @return the value of tb_order_extend.client_ip
     *
     * @mbg.generated
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.client_ip
     *
     * @param clientIp the value for tb_order_extend.client_ip
     *
     * @mbg.generated
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp == null ? null : clientIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.lodger_mobile
     *
     * @return the value of tb_order_extend.lodger_mobile
     *
     * @mbg.generated
     */
    public String getLodgerMobile() {
        return lodgerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.lodger_mobile
     *
     * @param lodgerMobile the value for tb_order_extend.lodger_mobile
     *
     * @mbg.generated
     */
    public void setLodgerMobile(String lodgerMobile) {
        this.lodgerMobile = lodgerMobile == null ? null : lodgerMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.lodger_name
     *
     * @return the value of tb_order_extend.lodger_name
     *
     * @mbg.generated
     */
    public String getLodgerName() {
        return lodgerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.lodger_name
     *
     * @param lodgerName the value for tb_order_extend.lodger_name
     *
     * @mbg.generated
     */
    public void setLodgerName(String lodgerName) {
        this.lodgerName = lodgerName == null ? null : lodgerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.landlord_name
     *
     * @return the value of tb_order_extend.landlord_name
     *
     * @mbg.generated
     */
    public String getLandlordName() {
        return landlordName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.landlord_name
     *
     * @param landlordName the value for tb_order_extend.landlord_name
     *
     * @mbg.generated
     */
    public void setLandlordName(String landlordName) {
        this.landlordName = landlordName == null ? null : landlordName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.landlord_mobile
     *
     * @return the value of tb_order_extend.landlord_mobile
     *
     * @mbg.generated
     */
    public String getLandlordMobile() {
        return landlordMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.landlord_mobile
     *
     * @param landlordMobile the value for tb_order_extend.landlord_mobile
     *
     * @mbg.generated
     */
    public void setLandlordMobile(String landlordMobile) {
        this.landlordMobile = landlordMobile == null ? null : landlordMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.custom_name
     *
     * @return the value of tb_order_extend.custom_name
     *
     * @mbg.generated
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.custom_name
     *
     * @param customName the value for tb_order_extend.custom_name
     *
     * @mbg.generated
     */
    public void setCustomName(String customName) {
        this.customName = customName == null ? null : customName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.custom_count
     *
     * @return the value of tb_order_extend.custom_count
     *
     * @mbg.generated
     */
    public Short getCustomCount() {
        return customCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.custom_count
     *
     * @param customCount the value for tb_order_extend.custom_count
     *
     * @mbg.generated
     */
    public void setCustomCount(Short customCount) {
        this.customCount = customCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.fine
     *
     * @return the value of tb_order_extend.fine
     *
     * @mbg.generated
     */
    public BigDecimal getFine() {
        return fine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.fine
     *
     * @param fine the value for tb_order_extend.fine
     *
     * @mbg.generated
     */
    public void setFine(BigDecimal fine) {
        this.fine = fine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.house_belong_city
     *
     * @return the value of tb_order_extend.house_belong_city
     *
     * @mbg.generated
     */
    public String getHouseBelongCity() {
        return houseBelongCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.house_belong_city
     *
     * @param houseBelongCity the value for tb_order_extend.house_belong_city
     *
     * @mbg.generated
     */
    public void setHouseBelongCity(String houseBelongCity) {
        this.houseBelongCity = houseBelongCity == null ? null : houseBelongCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.is_comment
     *
     * @return the value of tb_order_extend.is_comment
     *
     * @mbg.generated
     */
    public Byte getIsComment() {
        return isComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.is_comment
     *
     * @param isComment the value for tb_order_extend.is_comment
     *
     * @mbg.generated
     */
    public void setIsComment(Byte isComment) {
        this.isComment = isComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.is_delete_landlord
     *
     * @return the value of tb_order_extend.is_delete_landlord
     *
     * @mbg.generated
     */
    public Byte getIsDeleteLandlord() {
        return isDeleteLandlord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.is_delete_landlord
     *
     * @param isDeleteLandlord the value for tb_order_extend.is_delete_landlord
     *
     * @mbg.generated
     */
    public void setIsDeleteLandlord(Byte isDeleteLandlord) {
        this.isDeleteLandlord = isDeleteLandlord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.is_delete_trip
     *
     * @return the value of tb_order_extend.is_delete_trip
     *
     * @mbg.generated
     */
    public Byte getIsDeleteTrip() {
        return isDeleteTrip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.is_delete_trip
     *
     * @param isDeleteTrip the value for tb_order_extend.is_delete_trip
     *
     * @mbg.generated
     */
    public void setIsDeleteTrip(Byte isDeleteTrip) {
        this.isDeleteTrip = isDeleteTrip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.is_delete
     *
     * @return the value of tb_order_extend.is_delete
     *
     * @mbg.generated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.is_delete
     *
     * @param isDelete the value for tb_order_extend.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.lodger_to_landlord_note
     *
     * @return the value of tb_order_extend.lodger_to_landlord_note
     *
     * @mbg.generated
     */
    public String getLodgerToLandlordNote() {
        return lodgerToLandlordNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.lodger_to_landlord_note
     *
     * @param lodgerToLandlordNote the value for tb_order_extend.lodger_to_landlord_note
     *
     * @mbg.generated
     */
    public void setLodgerToLandlordNote(String lodgerToLandlordNote) {
        this.lodgerToLandlordNote = lodgerToLandlordNote == null ? null : lodgerToLandlordNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.landlord_card_no
     *
     * @return the value of tb_order_extend.landlord_card_no
     *
     * @mbg.generated
     */
    public Long getLandlordCardNo() {
        return landlordCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.landlord_card_no
     *
     * @param landlordCardNo the value for tb_order_extend.landlord_card_no
     *
     * @mbg.generated
     */
    public void setLandlordCardNo(Long landlordCardNo) {
        this.landlordCardNo = landlordCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.check_in_time
     *
     * @return the value of tb_order_extend.check_in_time
     *
     * @mbg.generated
     */
    public Date getCheckInTime() {
        return checkInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.check_in_time
     *
     * @param checkInTime the value for tb_order_extend.check_in_time
     *
     * @mbg.generated
     */
    public void setCheckInTime(Date checkInTime) {
        this.checkInTime = checkInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.fee
     *
     * @return the value of tb_order_extend.fee
     *
     * @mbg.generated
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.fee
     *
     * @param fee the value for tb_order_extend.fee
     *
     * @mbg.generated
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.lodger_card_no
     *
     * @return the value of tb_order_extend.lodger_card_no
     *
     * @mbg.generated
     */
    public Long getLodgerCardNo() {
        return lodgerCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.lodger_card_no
     *
     * @param lodgerCardNo the value for tb_order_extend.lodger_card_no
     *
     * @mbg.generated
     */
    public void setLodgerCardNo(Long lodgerCardNo) {
        this.lodgerCardNo = lodgerCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.accept_type
     *
     * @return the value of tb_order_extend.accept_type
     *
     * @mbg.generated
     */
    public Byte getAcceptType() {
        return acceptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.accept_type
     *
     * @param acceptType the value for tb_order_extend.accept_type
     *
     * @mbg.generated
     */
    public void setAcceptType(Byte acceptType) {
        this.acceptType = acceptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.order_status_history
     *
     * @return the value of tb_order_extend.order_status_history
     *
     * @mbg.generated
     */
    public Long getOrderStatusHistory() {
        return orderStatusHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.order_status_history
     *
     * @param orderStatusHistory the value for tb_order_extend.order_status_history
     *
     * @mbg.generated
     */
    public void setOrderStatusHistory(Long orderStatusHistory) {
        this.orderStatusHistory = orderStatusHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.house_belong_city_name
     *
     * @return the value of tb_order_extend.house_belong_city_name
     *
     * @mbg.generated
     */
    public String getHouseBelongCityName() {
        return houseBelongCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.house_belong_city_name
     *
     * @param houseBelongCityName the value for tb_order_extend.house_belong_city_name
     *
     * @mbg.generated
     */
    public void setHouseBelongCityName(String houseBelongCityName) {
        this.houseBelongCityName = houseBelongCityName == null ? null : houseBelongCityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.activity_id
     *
     * @return the value of tb_order_extend.activity_id
     *
     * @mbg.generated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.activity_id
     *
     * @param activityId the value for tb_order_extend.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.of_id
     *
     * @return the value of tb_order_extend.of_id
     *
     * @mbg.generated
     */
    public Integer getOfId() {
        return ofId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.of_id
     *
     * @param ofId the value for tb_order_extend.of_id
     *
     * @mbg.generated
     */
    public void setOfId(Integer ofId) {
        this.ofId = ofId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.fine_belong_landlord
     *
     * @return the value of tb_order_extend.fine_belong_landlord
     *
     * @mbg.generated
     */
    public BigDecimal getFineBelongLandlord() {
        return fineBelongLandlord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.fine_belong_landlord
     *
     * @param fineBelongLandlord the value for tb_order_extend.fine_belong_landlord
     *
     * @mbg.generated
     */
    public void setFineBelongLandlord(BigDecimal fineBelongLandlord) {
        this.fineBelongLandlord = fineBelongLandlord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.deposit_online
     *
     * @return the value of tb_order_extend.deposit_online
     *
     * @mbg.generated
     */
    public BigDecimal getDepositOnline() {
        return depositOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.deposit_online
     *
     * @param depositOnline the value for tb_order_extend.deposit_online
     *
     * @mbg.generated
     */
    public void setDepositOnline(BigDecimal depositOnline) {
        this.depositOnline = depositOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.deposit_offline
     *
     * @return the value of tb_order_extend.deposit_offline
     *
     * @mbg.generated
     */
    public BigDecimal getDepositOffline() {
        return depositOffline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.deposit_offline
     *
     * @param depositOffline the value for tb_order_extend.deposit_offline
     *
     * @mbg.generated
     */
    public void setDepositOffline(BigDecimal depositOffline) {
        this.depositOffline = depositOffline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.need_reminder_number
     *
     * @return the value of tb_order_extend.need_reminder_number
     *
     * @mbg.generated
     */
    public String getNeedReminderNumber() {
        return needReminderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.need_reminder_number
     *
     * @param needReminderNumber the value for tb_order_extend.need_reminder_number
     *
     * @mbg.generated
     */
    public void setNeedReminderNumber(String needReminderNumber) {
        this.needReminderNumber = needReminderNumber == null ? null : needReminderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.real_reminder_number
     *
     * @return the value of tb_order_extend.real_reminder_number
     *
     * @mbg.generated
     */
    public String getRealReminderNumber() {
        return realReminderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.real_reminder_number
     *
     * @param realReminderNumber the value for tb_order_extend.real_reminder_number
     *
     * @mbg.generated
     */
    public void setRealReminderNumber(String realReminderNumber) {
        this.realReminderNumber = realReminderNumber == null ? null : realReminderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.ch_id
     *
     * @return the value of tb_order_extend.ch_id
     *
     * @mbg.generated
     */
    public String getChId() {
        return chId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.ch_id
     *
     * @param chId the value for tb_order_extend.ch_id
     *
     * @mbg.generated
     */
    public void setChId(String chId) {
        this.chId = chId == null ? null : chId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.if_id
     *
     * @return the value of tb_order_extend.if_id
     *
     * @mbg.generated
     */
    public String getIfId() {
        return ifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.if_id
     *
     * @param ifId the value for tb_order_extend.if_id
     *
     * @mbg.generated
     */
    public void setIfId(String ifId) {
        this.ifId = ifId == null ? null : ifId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.business_type_id
     *
     * @return the value of tb_order_extend.business_type_id
     *
     * @mbg.generated
     */
    public String getBusinessTypeId() {
        return businessTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.business_type_id
     *
     * @param businessTypeId the value for tb_order_extend.business_type_id
     *
     * @mbg.generated
     */
    public void setBusinessTypeId(String businessTypeId) {
        this.businessTypeId = businessTypeId == null ? null : businessTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.district_name
     *
     * @return the value of tb_order_extend.district_name
     *
     * @mbg.generated
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.district_name
     *
     * @param districtName the value for tb_order_extend.district_name
     *
     * @mbg.generated
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.baidu_lat
     *
     * @return the value of tb_order_extend.baidu_lat
     *
     * @mbg.generated
     */
    public BigDecimal getBaiduLat() {
        return baiduLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.baidu_lat
     *
     * @param baiduLat the value for tb_order_extend.baidu_lat
     *
     * @mbg.generated
     */
    public void setBaiduLat(BigDecimal baiduLat) {
        this.baiduLat = baiduLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.baidu_lon
     *
     * @return the value of tb_order_extend.baidu_lon
     *
     * @mbg.generated
     */
    public BigDecimal getBaiduLon() {
        return baiduLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.baidu_lon
     *
     * @param baiduLon the value for tb_order_extend.baidu_lon
     *
     * @mbg.generated
     */
    public void setBaiduLon(BigDecimal baiduLon) {
        this.baiduLon = baiduLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.avatar_url
     *
     * @return the value of tb_order_extend.avatar_url
     *
     * @mbg.generated
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.avatar_url
     *
     * @param avatarUrl the value for tb_order_extend.avatar_url
     *
     * @mbg.generated
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.house_imag_url
     *
     * @return the value of tb_order_extend.house_imag_url
     *
     * @mbg.generated
     */
    public String getHouseImagUrl() {
        return houseImagUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.house_imag_url
     *
     * @param houseImagUrl the value for tb_order_extend.house_imag_url
     *
     * @mbg.generated
     */
    public void setHouseImagUrl(String houseImagUrl) {
        this.houseImagUrl = houseImagUrl == null ? null : houseImagUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.lodger_url
     *
     * @return the value of tb_order_extend.lodger_url
     *
     * @mbg.generated
     */
    public String getLodgerUrl() {
        return lodgerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.lodger_url
     *
     * @param lodgerUrl the value for tb_order_extend.lodger_url
     *
     * @mbg.generated
     */
    public void setLodgerUrl(String lodgerUrl) {
        this.lodgerUrl = lodgerUrl == null ? null : lodgerUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.type
     *
     * @return the value of tb_order_extend.type
     *
     * @mbg.generated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.type
     *
     * @param type the value for tb_order_extend.type
     *
     * @mbg.generated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.close_type
     *
     * @return the value of tb_order_extend.close_type
     *
     * @mbg.generated
     */
    public String getCloseType() {
        return closeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.close_type
     *
     * @param closeType the value for tb_order_extend.close_type
     *
     * @mbg.generated
     */
    public void setCloseType(String closeType) {
        this.closeType = closeType == null ? null : closeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.refuse_desc
     *
     * @return the value of tb_order_extend.refuse_desc
     *
     * @mbg.generated
     */
    public String getRefuseDesc() {
        return refuseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.refuse_desc
     *
     * @param refuseDesc the value for tb_order_extend.refuse_desc
     *
     * @mbg.generated
     */
    public void setRefuseDesc(String refuseDesc) {
        this.refuseDesc = refuseDesc == null ? null : refuseDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.mvt_config
     *
     * @return the value of tb_order_extend.mvt_config
     *
     * @mbg.generated
     */
    public String getMvtConfig() {
        return mvtConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.mvt_config
     *
     * @param mvtConfig the value for tb_order_extend.mvt_config
     *
     * @mbg.generated
     */
    public void setMvtConfig(String mvtConfig) {
        this.mvtConfig = mvtConfig == null ? null : mvtConfig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.google_lat
     *
     * @return the value of tb_order_extend.google_lat
     *
     * @mbg.generated
     */
    public BigDecimal getGoogleLat() {
        return googleLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.google_lat
     *
     * @param googleLat the value for tb_order_extend.google_lat
     *
     * @mbg.generated
     */
    public void setGoogleLat(BigDecimal googleLat) {
        this.googleLat = googleLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.google_lon
     *
     * @return the value of tb_order_extend.google_lon
     *
     * @mbg.generated
     */
    public BigDecimal getGoogleLon() {
        return googleLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.google_lon
     *
     * @param googleLon the value for tb_order_extend.google_lon
     *
     * @mbg.generated
     */
    public void setGoogleLon(BigDecimal googleLon) {
        this.googleLon = googleLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.district_id
     *
     * @return the value of tb_order_extend.district_id
     *
     * @mbg.generated
     */
    public String getDistrictId() {
        return districtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.district_id
     *
     * @param districtId the value for tb_order_extend.district_id
     *
     * @mbg.generated
     */
    public void setDistrictId(String districtId) {
        this.districtId = districtId == null ? null : districtId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.ch_content
     *
     * @return the value of tb_order_extend.ch_content
     *
     * @mbg.generated
     */
    public String getChContent() {
        return chContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.ch_content
     *
     * @param chContent the value for tb_order_extend.ch_content
     *
     * @mbg.generated
     */
    public void setChContent(String chContent) {
        this.chContent = chContent == null ? null : chContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.business_id
     *
     * @return the value of tb_order_extend.business_id
     *
     * @mbg.generated
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.business_id
     *
     * @param businessId the value for tb_order_extend.business_id
     *
     * @mbg.generated
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend._timestamp
     *
     * @return the value of tb_order_extend._timestamp
     *
     * @mbg.generated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend._timestamp
     *
     * @param timestamp the value for tb_order_extend._timestamp
     *
     * @mbg.generated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.pay_percent
     *
     * @return the value of tb_order_extend.pay_percent
     *
     * @mbg.generated
     */
    public BigDecimal getPayPercent() {
        return payPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.pay_percent
     *
     * @param payPercent the value for tb_order_extend.pay_percent
     *
     * @mbg.generated
     */
    public void setPayPercent(BigDecimal payPercent) {
        this.payPercent = payPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.house_belong_province
     *
     * @return the value of tb_order_extend.house_belong_province
     *
     * @mbg.generated
     */
    public Long getHouseBelongProvince() {
        return houseBelongProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.house_belong_province
     *
     * @param houseBelongProvince the value for tb_order_extend.house_belong_province
     *
     * @mbg.generated
     */
    public void setHouseBelongProvince(Long houseBelongProvince) {
        this.houseBelongProvince = houseBelongProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.house_belong_province_name
     *
     * @return the value of tb_order_extend.house_belong_province_name
     *
     * @mbg.generated
     */
    public String getHouseBelongProvinceName() {
        return houseBelongProvinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.house_belong_province_name
     *
     * @param houseBelongProvinceName the value for tb_order_extend.house_belong_province_name
     *
     * @mbg.generated
     */
    public void setHouseBelongProvinceName(String houseBelongProvinceName) {
        this.houseBelongProvinceName = houseBelongProvinceName == null ? null : houseBelongProvinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_extend.extend_info
     *
     * @return the value of tb_order_extend.extend_info
     *
     * @mbg.generated
     */
    public String getExtendInfo() {
        return extendInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_extend.extend_info
     *
     * @param extendInfo the value for tb_order_extend.extend_info
     *
     * @mbg.generated
     */
    public void setExtendInfo(String extendInfo) {
        this.extendInfo = extendInfo == null ? null : extendInfo.trim();
    }
}