package com.exercise.demo.model.po.order;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_auth
 */
public class UserAuth {
    /**
     * Database Column Remarks:
     *   自增id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   登录类型（手机号 邮箱 用户名）或第三方应用名称（微信 微博等）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.identity_type
     *
     * @mbg.generated
     */
    private Byte identityType;

    /**
     * Database Column Remarks:
     *   标识（手机号 邮箱 用户名或第三方应用的唯一标识）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.identifier
     *
     * @mbg.generated
     */
    private String identifier;

    /**
     * Database Column Remarks:
     *   密码凭证（站内的保存密码，站外的不保存或保存token）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.credential
     *
     * @mbg.generated
     */
    private String credential;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auth.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.id
     *
     * @return the value of user_auth.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.id
     *
     * @param id the value for user_auth.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.user_id
     *
     * @return the value of user_auth.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.user_id
     *
     * @param userId the value for user_auth.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.identity_type
     *
     * @return the value of user_auth.identity_type
     *
     * @mbg.generated
     */
    public Byte getIdentityType() {
        return identityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.identity_type
     *
     * @param identityType the value for user_auth.identity_type
     *
     * @mbg.generated
     */
    public void setIdentityType(Byte identityType) {
        this.identityType = identityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.identifier
     *
     * @return the value of user_auth.identifier
     *
     * @mbg.generated
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.identifier
     *
     * @param identifier the value for user_auth.identifier
     *
     * @mbg.generated
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier == null ? null : identifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.credential
     *
     * @return the value of user_auth.credential
     *
     * @mbg.generated
     */
    public String getCredential() {
        return credential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.credential
     *
     * @param credential the value for user_auth.credential
     *
     * @mbg.generated
     */
    public void setCredential(String credential) {
        this.credential = credential == null ? null : credential.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.create_time
     *
     * @return the value of user_auth.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.create_time
     *
     * @param createTime the value for user_auth.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auth.update_time
     *
     * @return the value of user_auth.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auth.update_time
     *
     * @param updateTime the value for user_auth.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}