package com.exercise.demo.model.po.order;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table xide_user
 */
public class XideUser {
    /**
     * Database Column Remarks:
     *   主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xide_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   工号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xide_user.userNo
     *
     * @mbg.generated
     */
    private Long userno;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xide_user.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xide_user.id
     *
     * @return the value of xide_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xide_user.id
     *
     * @param id the value for xide_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xide_user.userNo
     *
     * @return the value of xide_user.userNo
     *
     * @mbg.generated
     */
    public Long getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xide_user.userNo
     *
     * @param userno the value for xide_user.userNo
     *
     * @mbg.generated
     */
    public void setUserno(Long userno) {
        this.userno = userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xide_user.userName
     *
     * @return the value of xide_user.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xide_user.userName
     *
     * @param username the value for xide_user.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}